---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:  
  name: hello-world-pipeline
spec:
  params:
    - name: message
  tasks:
    - name: echo
      taskRef:
        name: echo
      params:
        - name: message
          value: "$(params.message)"

---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  params:
    - name: repo-url
    - name: branch
      default: "main"
  tasks:
    - name: clone
      taskRef:
        name: checkout
      params:
        - name: repo-url
          value: "$(params.repo-url)"
        - name: branch
          value: "$(params.branch)"
    
    - name: echo-linting
      taskRef:
        name: echo
      params:
        - name: message
          value: "Calling Flake8 linter"
      runAfter: 
        - clone

    - name: lint
      taskRef:
        name: lint
      runAfter:
        - echo-linting
...
