---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:  
  name: hello-world-pipeline
spec:
  params:
    - name: message
  tasks:
    - name: echo
      taskRef:
        name: echo
      params:
        - name: message
          value: "$(params.message)"
...
