---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo
spec:
  params:
    - name: message
      type: string
      description: The message to echo
  steps:
    - name: echo-message
      # Practice Project uses Alpine Linux, a Linux distribution designed to be small, simple, and secure.
      image: alpine:3
      # Use "/bin/echo" instead of just "echo". Reason: "echo" is shell builtin.
      # May be the case that no shell is used, but the command is executed directly.
      command: [/bin/echo]
      args: ["$(params.message)"]
...
