---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-world
spec:
  steps:
    - name: echo
      # Practice Project uses Alpine Linux, a Linux distribution designed to be small, simple, and secure.
      image: alpine:3
      # Use "/bin/echo" instead of just "echo". Reason: "echo" is shell builtin.
      # May be the case that no shell is used, but the command is executed directly.
      command: [/bin/echo]
      args: ["Hello World / Tekton!"]
...